package com.faiveley.samng.vuegraphique.ihm.vues.vuegraphique;


/**
 * 
 * @author Cosmin Udroiu
 *
 */
public enum TypeMenuOptions {
	DISPLAY_AXE_TEMPS,
	DISPLAY_AXE_TEMPS_CORRIGE,
	DISPLAY_AXE_DISTANCE,
	DISPLAY_AXE_DISTANCE_CORRIGE,
	PREVIOUS_ZOOM,
	NEXT_ZOOM,
	MAIN_ZOOM,
	MANUAL_ZOOM, 
	FILTER_MANAGEMENT, 
	STEPPED_GRAPH,
	DIGITAL_ZERO_REF,
	DISPLAY_LABEL,
	USE_SHORT_NAMES,
	DISPLAY_TIME_BREAKS,
	DISPLAY_DISTANCE_BREAKS,
	DISPLAY_MARKERS,
	LINE_MODE,
	POINT_MODE,
	WHITE_BACKGROUND,
	NO_FILTER
}
