//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.06 at 03:12:18 PM CET 
//


package com.faiveley.samng.principal.sm.missions.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.faiveley.samng.principal.sm.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Document_QNAME = new QName("", "document");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.faiveley.samng.principal.sm.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TypeRegroupementTemps }
     * 
     */
    public TypeRegroupementTemps createTypeRegroupementTemps() {
        return new TypeRegroupementTemps();
    }

    /**
     * Create an instance of {@link TypeSegment }
     * 
     */
    public TypeSegment createTypeSegment() {
        return new TypeSegment();
    }

    /**
     * Create an instance of {@link TypeListeRegroupementTemps }
     * 
     */
    public TypeListeRegroupementTemps createTypeListeRegroupementTemps() {
        return new TypeListeRegroupementTemps();
    }

    /**
     * Create an instance of {@link TypeDocument }
     * 
     */
    public TypeDocument createTypeDocument() {
        return new TypeDocument();
    }

    /**
     * Create an instance of {@link TypeListeSegment }
     * 
     */
    public TypeListeSegment createTypeListeSegment() {
        return new TypeListeSegment();
    }

    /**
     * Create an instance of {@link TypeRefMission }
     * 
     */
    public TypeRefMission createTypeRefMission() {
        return new TypeRefMission();
    }

    /**
     * Create an instance of {@link TypeMission }
     * 
     */
    public TypeMission createTypeMission() {
        return new TypeMission();
    }

    /**
     * Create an instance of {@link TypeListeRefMission }
     * 
     */
    public TypeListeRefMission createTypeListeRefMission() {
        return new TypeListeRefMission();
    }

    /**
     * Create an instance of {@link TypeListeMission }
     * 
     */
    public TypeListeMission createTypeListeMission() {
        return new TypeListeMission();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TypeDocument }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "document")
    public JAXBElement<TypeDocument> createDocument(TypeDocument value) {
        return new JAXBElement<TypeDocument>(_Document_QNAME, TypeDocument.class, null, value);
    }

}
