//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.06 at 03:12:18 PM CET 
//


package com.faiveley.samng.principal.sm.missions.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for typeDocument complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="typeDocument">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ListeMission" type="{}typeListeMission"/>
 *         &lt;element name="ListeRegoupementTemps" type="{}typeListeRegroupementTemps"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */

@XmlRootElement(name="document")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "typeDocument", propOrder = {
    "listeMission",
    "listeRegoupementTemps"
})
public class TypeDocument {

    @XmlElement(name = "ListeMission", required = true)
    protected TypeListeMission listeMission;
    @XmlElement(name = "ListeRegoupementTemps", required = true)
    protected TypeListeRegroupementTemps listeRegoupementTemps;

    /**
     * Gets the value of the listeMission property.
     * 
     * @return
     *     possible object is
     *     {@link TypeListeMission }
     *     
     */
    public TypeListeMission getListeMission() {
        return listeMission;
    }

    /**
     * Sets the value of the listeMission property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeListeMission }
     *     
     */
    public void setListeMission(TypeListeMission value) {
        this.listeMission = value;
    }

    /**
     * Gets the value of the listeRegoupementTemps property.
     * 
     * @return
     *     possible object is
     *     {@link TypeListeRegroupementTemps }
     *     
     */
    public TypeListeRegroupementTemps getListeRegoupementTemps() {
        return listeRegoupementTemps;
    }

    /**
     * Sets the value of the listeRegoupementTemps property.
     * 
     * @param value
     *     allowed object is
     *     {@link TypeListeRegroupementTemps }
     *     
     */
    public void setListeRegoupementTemps(TypeListeRegroupementTemps value) {
        this.listeRegoupementTemps = value;
    }

}
