//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.22 at 10:26:01 AM CET 
//


package com.faiveley.samng.principal.sm.parseconfigatess;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attGroup ref="{}attlist.entree-logique"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "entree-logique")
public class EntreeLogique {

    @XmlAttribute(name = "code-entree-logique", required = true)
    protected int codeEntreeLogique;
    @XmlAttribute(name = "valeur-entree-logique")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String valeurEntreeLogique;

    /**
     * Gets the value of the codeEntreeLogique property.
     * 
     */
    public int getCodeEntreeLogique() {
        return codeEntreeLogique;
    }

    /**
     * Sets the value of the codeEntreeLogique property.
     * 
     */
    public void setCodeEntreeLogique(int value) {
        this.codeEntreeLogique = value;
    }

    /**
     * Gets the value of the valeurEntreeLogique property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValeurEntreeLogique() {
        if (valeurEntreeLogique == null) {
            return "false";
        } else {
            return valeurEntreeLogique;
        }
    }

    /**
     * Sets the value of the valeurEntreeLogique property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValeurEntreeLogique(String value) {
        this.valeurEntreeLogique = value;
    }

}
