//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.22 at 10:26:01 AM CET 
//


package com.faiveley.samng.principal.sm.parseconfigatess;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}liste-variables-atess" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}entree-logique" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{}attlist.evenement-variables"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "listeVariablesAtess",
    "entreeLogique"
})
@XmlRootElement(name = "evenement-variables")
public class EvenementVariables {

    @XmlElement(name = "liste-variables-atess")
    protected List<ListeVariablesAtess> listeVariablesAtess;
    @XmlElement(name = "entree-logique")
    protected EntreeLogique entreeLogique;
    @XmlAttribute(name = "code-evt", required = true)
    protected int codeEvt;
    @XmlAttribute(required = true)
    protected int longueur;

    /**
     * Gets the value of the listeVariablesAtess property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the listeVariablesAtess property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getListeVariablesAtess().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ListeVariablesAtess }
     * 
     * 
     */
    public List<ListeVariablesAtess> getListeVariablesAtess() {
        if (listeVariablesAtess == null) {
            listeVariablesAtess = new ArrayList<ListeVariablesAtess>();
        }
        return this.listeVariablesAtess;
    }

    /**
     * Gets the value of the entreeLogique property.
     * 
     * @return
     *     possible object is
     *     {@link EntreeLogique }
     *     
     */
    public EntreeLogique getEntreeLogique() {
        return entreeLogique;
    }

    /**
     * Sets the value of the entreeLogique property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntreeLogique }
     *     
     */
    public void setEntreeLogique(EntreeLogique value) {
        this.entreeLogique = value;
    }

    /**
     * Gets the value of the codeEvt property.
     * 
     */
    public int getCodeEvt() {
        return codeEvt;
    }

    /**
     * Sets the value of the codeEvt property.
     * 
     */
    public void setCodeEvt(int value) {
        this.codeEvt = value;
    }

    /**
     * Gets the value of the longueur property.
     * 
     */
    public int getLongueur() {
        return longueur;
    }

    /**
     * Sets the value of the longueur property.
     * 
     */
    public void setLongueur(int value) {
        this.longueur = value;
    }

}
