//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.22 at 10:26:01 AM CET 
//


package com.faiveley.samng.principal.sm.parseconfigatess;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}compteur-temps"/>
 *         &lt;element ref="{}compteur-distance"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "compteurTemps",
    "compteurDistance"
})
@XmlRootElement(name = "liste-maximum-compteur")
public class ListeMaximumCompteur {

    @XmlElement(name = "compteur-temps", required = true)
    protected CompteurTemps compteurTemps;
    @XmlElement(name = "compteur-distance", required = true)
    protected CompteurDistance compteurDistance;

    /**
     * Gets the value of the compteurTemps property.
     * 
     * @return
     *     possible object is
     *     {@link CompteurTemps }
     *     
     */
    public CompteurTemps getCompteurTemps() {
        return compteurTemps;
    }

    /**
     * Sets the value of the compteurTemps property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompteurTemps }
     *     
     */
    public void setCompteurTemps(CompteurTemps value) {
        this.compteurTemps = value;
    }

    /**
     * Gets the value of the compteurDistance property.
     * 
     * @return
     *     possible object is
     *     {@link CompteurDistance }
     *     
     */
    public CompteurDistance getCompteurDistance() {
        return compteurDistance;
    }

    /**
     * Sets the value of the compteurDistance property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompteurDistance }
     *     
     */
    public void setCompteurDistance(CompteurDistance value) {
        this.compteurDistance = value;
    }

}
