//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.22 at 10:26:01 AM CET 
//


package com.faiveley.samng.principal.sm.parseconfigatess;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pack package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pack
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link EvenementVariables }
     * 
     */
    public EvenementVariables createEvenementVariables() {
        return new EvenementVariables();
    }

    /**
     * Create an instance of {@link CompteurTemps }
     * 
     */
    public CompteurTemps createCompteurTemps() {
        return new CompteurTemps();
    }

    /**
     * Create an instance of {@link VariableAtess }
     * 
     */
    public VariableAtess createVariableAtess() {
        return new VariableAtess();
    }

    /**
     * Create an instance of {@link FichierDescription }
     * 
     */
    public FichierDescription createFichierDescription() {
        return new FichierDescription();
    }

    /**
     * Create an instance of {@link ListeVariablesAtess }
     * 
     */
    public ListeVariablesAtess createListeVariablesAtess() {
        return new ListeVariablesAtess();
    }

    /**
     * Create an instance of {@link Identifiant }
     * 
     */
    public Identifiant createIdentifiant() {
        return new Identifiant();
    }

    /**
     * Create an instance of {@link ListeMaximumCompteur }
     * 
     */
    public ListeMaximumCompteur createListeMaximumCompteur() {
        return new ListeMaximumCompteur();
    }

    /**
     * Create an instance of {@link Signature }
     * 
     */
    public Signature createSignature() {
        return new Signature();
    }

    /**
     * Create an instance of {@link CompteurDistance }
     * 
     */
    public CompteurDistance createCompteurDistance() {
        return new CompteurDistance();
    }

    /**
     * Create an instance of {@link TableEvenementsVariables }
     * 
     */
    public TableEvenementsVariables createTableEvenementsVariables() {
        return new TableEvenementsVariables();
    }

    /**
     * Create an instance of {@link ListeIdentifiantsEtendus }
     * 
     */
    public ListeIdentifiantsEtendus createListeIdentifiantsEtendus() {
        return new ListeIdentifiantsEtendus();
    }

    /**
     * Create an instance of {@link EntreeLogique }
     * 
     */
    public EntreeLogique createEntreeLogique() {
        return new EntreeLogique();
    }

    /**
     * Create an instance of {@link ConfigurationAtess }
     * 
     */
    public ConfigurationAtess createConfigurationAtess() {
        return new ConfigurationAtess();
    }

}
